# Configuration for Garmin/Strava Google Sheets Sync
# Choose whether to sync from Garmin or Strava. Options: garmin, strava
sync_source: garmin

# Set to true to print all values of the most recent activity for debugging
debug: false
