[project]
name = "garmin-sheet"
version = "0.1.0"
description = "Sync Garmin stats to Google Sheets"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "garminconnect",
    "requests",
    "python-dotenv",
    "curl-cffi>=0.15.0",
    "pandas>=3.0.2",
    "gspread",
    "google-cloud-secret-manager",
    "strava-client>=1.0.7",
    "ipykernel>=7.3.0",
    "openpyxl>=3.1.5",
    "seaborn>=0.13.2",
    "matplotlib>=3.11.0",
]
